-- MySQL Script generated by MySQL Workbench
-- Sat Oct 22 18:56:31 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema trains
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema trains
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trains` DEFAULT CHARACTER SET utf8 ;
USE `trains` ;

-- -----------------------------------------------------
-- Table `trains`.`Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trains`.`Account` ;

CREATE TABLE IF NOT EXISTS `trains`.`Account` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `reference_id` VARCHAR(255) NOT NULL,
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `enabled` BIT(1) NOT NULL DEFAULT b'1',
  `credentialsexpired` BIT(1) NOT NULL DEFAULT b'0',
  `expired` BIT(1) NOT NULL DEFAULT b'0',
  `locked` BIT(1) NOT NULL DEFAULT b'0',
  `version` INT(10) UNSIGNED NOT NULL,
  `created_by` VARCHAR(100) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_by` VARCHAR(100) NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UQ_Account_ReferenceId` (`reference_id` ASC),
  UNIQUE INDEX `UQ_Account_Username` (`username` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `trains`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trains`.`Role` ;

CREATE TABLE IF NOT EXISTS `trains`.`Role` (
  `id` BIGINT(20) UNSIGNED NOT NULL,
  `code` VARCHAR(50) NOT NULL,
  `label` VARCHAR(100) NOT NULL,
  `ordinal` INT(10) UNSIGNED NOT NULL,
  `effective_at` DATETIME NOT NULL,
  `expires_at` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UQ_Role_Code` (`code` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `trains`.`account_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `trains`.`account_role` ;

CREATE TABLE IF NOT EXISTS `trains`.`account_role` (
  `account_id` BIGINT(20) UNSIGNED NOT NULL,
  `role_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`account_id`, `role_id`),
  INDEX `FK_account_role_role_id` (`role_id` ASC),
  CONSTRAINT `FK_account_role_Account_Id`
    FOREIGN KEY (`account_id`)
    REFERENCES `trains`.`Account` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `FK_account_role_Role_Id`
    FOREIGN KEY (`role_id`)
    REFERENCES `trains`.`Role` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
